plugins:
    - prettier

extends:
    - eslint:recommended
    - google

rules:
    indent: [error, 2]
    quotes: [2, single, {allowTemplateLiterals: true}]
    semi: [error, always]
    comma-dangle: [error, never]
    no-unused-vars: warn
    no-var: 1 # use var just for browser
    spaced-comment: off
    max-len: [error, 120]
    arrow-parens: [2, always]
    object-curly-spacing: [error, always]
    no-invalid-this: off
    new-cap: off

env:
    browser: true
    es6: true

parserOptions:
    ecmaVersion: 2018
    sourceType: module

globals:
    importScripts: false
    workbox: false
