language: node_js
node_js:
  - "12"
  - "11"

sudo: false

branches:
  only:
    - master

before_install:
  # yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH
  # tree
  - sudo apt-get install tree

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  # linting javascript and scss
  - yarn lint
  # build source
  - yarn build

after_success:
  # show output tree
  - cd ./dist && tree
  # netlify soon!
