language: node_js
node_js:
  - "12"
  - "11"

sudo: false

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  # https://docs.fossa.com/docs/travisci
  - fossa init
  - fossa analyze

  # linting javascript and scss
  - yarn lint
  # build source
  - yarn build

after_success:
  - cd ./dist && fossa test
